services:
  mariadb:
    image: docker.io/library/mariadb:11.6.2
    container_name: mariadb.arbor-lwa.local
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: "arbor"
      MARIADB_DATABASE: "arbor"
      MARIADB_USER: "arbor"
      MARIADB_PASSWORD: "arbor"
    ports:
      - "3306:3306"
    networks:
      - arbor-lwa-network

  elasticsearch:
    image: docker.io/library/elasticsearch:8.17.1
    container_name: elasticsearch.arbor-lwa.local
    restart: unless-stopped
    environment:
      discovery.type: "single-node"
      xpack.security.enabled: "false"
    ports:
      - "9200:9200"
    networks:
      - arbor-lwa-network

  redis:
    image: docker.io/library/redis:7.4.2
    container_name: redis.arbor-lwa.local
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - arbor-lwa-network

  backend:
    build:
      context: ../../backend
    image: arbor-lwa-backend
    container_name: backend.arbor-lwa.local
    restart: unless-stopped
    depends_on:
      - mariadb
      - elasticsearch
      - redis
    environment:
      DB_USER: "arbor"
      DB_PASSWORD: "arbor"
      DB_HOST: "mariadb.arbor-lwa.local"
      DB_PORT: "3306"
      DB_NAME: "arbor"
      REDIS_HOST: "redis.arbor-lwa.local"
      REDIS_PORT: "6379"
      ELASTICSEARCH_HOST: "elasticsearch.arbor-lwa.local"
      ELASTICSEARCH_PORT: "9200"
      JWT_SECRET_KEY: "arbor1234567890arbor1234567890arbor1234567890"
      SEED_BOOK_COUNT: "221"
    ports:
      - "5000:5000"
    networks:
      - arbor-lwa-network
    command: >
      /bin/sh -c "sleep 30 && python app.py"

  frontend:
    build:
      context: ../../frontend
    image: arbor-lwa-frontend
    container_name: frontend.arbor-lwa.local
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "8080:80"
    networks:
      - arbor-lwa-network
    command: >
      /bin/sh -c "nginx -g 'daemon off;'"

networks:
  arbor-lwa-network:
    driver: bridge
